// PRODUCTS
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCTS_HIDDEN = 'FETCH_PRODUCTS_HIDDEN';
export const FETCH_PRODUCTS_ERROR = 'FETCH_PRODUCTS_ERROR';
export const FETCH_PRODUCT_BY_ID = 'FETCH_PRODUCT_BY_ID';
export const FETCH_PRODUCT_BY_ID_ERROR = 'FETCH_PRODUCT_BY_ID_ERROR';
export const HIDE_PRODUCT = 'HIDE_PRODUCT';
export const HIDE_PRODUCT_ERROR = 'HIDE_PRODUCT_ERROR';
export const CREATE_PRODUCT_REQUEST = 'CREATE_PRODUCT_REQUEST';
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS';
export const CREATE_PRODUCT_ERROR = 'CREATE_PRODUCT_ERROR';
export const RESTORE_PRODUCT = 'RESTORE_PRODUCT';
export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const UPDATE_PRODUCT_ERROR = 'UPDATE_PRODUCT_ERROR';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const DELETE_PRODUCT_ERROR = 'DELETE_PRODUCT_ERROR';

// ORDERS
export const CREATE_ORDER = 'CREATE_ORDER';
export const CREATE_ORDER_ERROR = 'CREATE_ORDER_ERROR';
export const FETCH_USER_ORDERS = 'FETCH_USER_ORDERS';
export const FETCH_USER_ORDERS_ERROR = 'FETCH_USER_ORDERS_ERROR';
export const FETCH_ORDER_BY_ID = 'FETCH_ORDER_BY_ID';
export const FETCH_ORDER_BY_ID_ERROR = 'FETCH_ORDER_BY_ID_ERROR';
export const FETCH_ALL_ORDERS = 'FETCH_ALL_ORDERS';
export const FETCH_ALL_ORDERS_ERROR = 'FETCH_ALL_ORDERS_ERROR';
export const UPDATE_ORDER_STATUS = 'UPDATE_ORDER_STATUS';
export const UPDATE_ORDER_STATUS_ERROR = 'UPDATE_ORDER_STATUS_ERROR';

// IMPORTS
export const IMPORT_STOCK = 'IMPORT_STOCK';
export const IMPORT_STOCK_ERROR = 'IMPORT_STOCK_ERROR';
export const ADJUST_STOCK = 'ADJUST_STOCK';
export const ADJUST_STOCK_ERROR = 'ADJUST_STOCK_ERROR';
export const FETCH_INVENTORY_TRANSACTIONS = 'FETCH_INVENTORY_TRANSACTIONS';
export const FETCH_INVENTORY_TRANSACTIONS_ERROR = 'FETCH_INVENTORY_TRANSACTIONS_ERROR';

// ADMIN
export const FETCH_REPORTS_DASHBOARD = 'FETCH_REPORTS_DASHBOARD';
export const FETCH_REPORTS_DASHBOARD_ERROR = 'FETCH_REPORTS_DASHBOARD_ERROR';
export const FETCH_INVENTORY_REPORT = 'FETCH_INVENTORY_REPORT';
export const FETCH_INVENTORY_REPORT_ERROR = 'FETCH_INVENTORY_REPORT_ERROR';
export const FETCH_EXPORT_REPORT = 'FETCH_EXPORT_REPORT';
export const FETCH_EXPORT_REPORT_ERROR = 'FETCH_EXPORT_REPORT_ERROR';
export const FETCH_REVENUE_REPORT = 'FETCH_REVENUE_REPORT';
export const FETCH_REVENUE_REPORT_ERROR = 'FETCH_REVENUE_REPORT_ERROR';

export const FETCH_EXPENSES = 'FETCH_EXPENSES';
export const FETCH_EXPENSES_SUCCESS = 'FETCH_EXPENSES_SUCCESS';
export const FETCH_EXPENSES_ERROR = 'FETCH_EXPENSES_ERROR';
export const FETCH_HIDDEN_EXPENSES = 'FETCH_HIDDEN_EXPENSES';
export const FETCH_HIDDEN_EXPENSES_SUCCESS = 'FETCH_HIDDEN_EXPENSES_SUCCESS';
export const FETCH_HIDDEN_EXPENSES_ERROR = 'FETCH_HIDDEN_EXPENSES_ERROR';
export const CREATE_EXPENSE = 'CREATE_EXPENSE';
export const UPDATE_EXPENSE = 'UPDATE_EXPENSE';
export const DELETE_EXPENSE = 'DELETE_EXPENSE';
export const HIDE_EXPENSE = 'HIDE_EXPENSE';
export const RESTORE_EXPENSE = 'RESTORE_EXPENSE';